### ISSUE TITLE
Lost with Gulp

### ISSUE THREAD

**Issue by lionel-m** [corysimmons/lost#11]
Hi,

I tried to use lost with Gulp but it does not work with this syntax: `.pipe(stylus({use: [rupture(), lost()]}))`

I solved the problem by using the code of "rupture" ([`index.js`](https://github.com/jenius/rupture/blob/master/index.js)). Or should I write differently?

Thank you for this excellent project!

**Comment by corysimmons** [comment]
Did you `@import 'lost'` at the top of your stylesheet?

**Comment by corysimmons** [comment]
Thanks!

**Comment by lionel-m** [comment]
Ok it was my mistake... I'm new with Gulp. Because "rupture" works without adding `@import 'rupture' ` I have not thought to add it for lost.

It is ok now. Thanks for your help!

**Comment by corysimmons** [comment]
The reason I'm setting it up like this instead of "implicitly" requiring it, is so that in the future I can migrate the `settings` out into their own file.

So the project structure would look like this:

```
- bower_components
  - lost-grid
    - stylus
      - lost-settings.styl
      - lost-grid.styl
- my-project
  - css
    - lost-settings.styl
    - style.styl (with @import '../bower_components/lost-grid')
```

This way we could leave the `bower_components` (or however you're importing it) completely alone, and then just override settings in our project-specific `lost-settings.styl`file.

By requiring it implicitly, we say "don't give the user a chance to override defaults".

Closing this, but will open an issue for creating this kind of override scheme.

**Comment by corysimmons** [comment]
https://github.com/corysimmons/lost/issues/13

**Comment by corysimmons** [comment]
@lionel-m This settings override feature has been added. Now you can simply `@import` Lost. Then modify any of the settings variables. Then you can use any of the mixins and it will work. =)

**Comment by lionel-m** [comment]
Thanks!

**Comment by corysimmons** [comment]
:+1:
