### ISSUE TITLE
remove stylus support refs in readme

### ISSUE THREAD

**Issue by kylemac** [corysimmons/lost#114]
i hadn't realized the change from 5.x to 6.0.1 removed stylus support due to the fact that it's still present in the readme.

**Comment by corysimmons** [comment]
It still supports Stylus, and every other preprocess, and vanilla CSS now.

I'm using it with Stylus in the demo https://github.com/corysimmons/lost/tree/gh-pages

**Comment by kylemac** [comment]
I guess I assumed "stylus support" meant stylus middleware. i'm probably confused because i'm not sure what post-css does, yet. nonetheless, my stylus implementations broke and i saw this: 

![screen shot 2015-04-29 at 11 35 04 am](https://cloud.githubusercontent.com/assets/49507/7394782/d314f15c-ee63-11e4-9e15-5940e6b800ad.png)

**Comment by corysimmons** [comment]
PostCSS basically takes compiled CSS and runs it through JS so you can perform operations on it after it's been compiled. You need to use it with a task runner like Grunt or Gulp most of the time but it also has a CLI tool.

So PostCSS might look like this:

Input:
```css
.foo {
  my-background-function: red;
}
```

Output:
```css
.foo {
  background-color: red;
}
```

The README still states support for Stylus/etc. because it *does* support those workflows whereas it's competing grids might not.

Sorry if your implementations broke. It was a major release and I left a note about it and updated the README to reflect the new changes.

I know it is a big change, but I think a lot of [things](https://twitter.com/mdo/status/591364406816079873) are moving over to PostCSS for good reason. Now I don't have to support 3 codebases to support all the preprocessors, *and* it supports vanilla CSS now.

I probably should've left this repo as the Stylus/SCSS/LESS ports, but then I would have **4** codebases to maintain.

People have been asking for it for months and it just seemed like the logical thing to do.

**Comment by kylemac** [comment]
don't sweat it - you did the right thing by making a point release and leaving a trail. i understand your point about support as well. thanks for the rundown on post-css as well

**Comment by corysimmons** [comment]
:+1: 

I hope you (& Co.?) will keep using it. It is definitely better than what's out there in almost every category I can think of.

So far as Stylus middleware goes, I would love to see something like https://github.com/jenius/autoprefixer-stylus for Lost but I'm not skilled enough to do it. I'm also not sure Lost exposes itself as cleanly as autoprefixer-core does. On the other hand, it might be completely trivial for someone like you *wink wink nudge nudge*. :)

**Comment by corysimmons** [comment]
Also, heads up, I'll be removing default cycling soon (tonight?) https://github.com/corysimmons/lost/issues/109 but it will be a major release and after that the API should be pretty stable.

**Comment by corysimmons** [comment]
Scratch that, I decided not to break the API. Auto-`cycle` is still the default.

**Comment by kylemac** [comment]
:+1:
