### ISSUE TITLE
lost-move: a full width block isnt working

### ISSUE THREAD

**Issue by maxisix** [corysimmons/lost#152]
tried to move 2 full width block like this and its not working

div:first-child {
  lost-move: 1;
}

div:last-child {
  lost-move: -1;
}

**Comment by corysimmons** [comment]
Doesn't work with `1/1` does it?

**Comment by flip4bytes** [comment]
All lost-move is doing is visually moving over an item to the right and left so on larger displays you are simply visually laying it out differently. No matter what, when you're dealing with a full width element (normally dealing with that on mobile) then it will always revert to the actual structure that the HTML is laid out.

e.g.

```
<div>First</div>
<div>Second</div>
```

In that above scenario, First is ALWAYS going to be first and second is ALWAYS going to be second when you have each div full-width. lost-move ONLY works when you say have both of those divs next to eachother and you want the second div and the first div to visually swap with eachother. Once you revert them back to be full-width then it's always going to go back to the first and second top to bottom because that's the physical structure layout.

What you're looking for is to change the ordering. Something that you have to use flexbox for (there's NO graceful way to reorder the physical structure of html elements without getting EXTREMELY messy with position absolute top/bottom numbers and stuff). Look up flexbox ordering and you can mix flexbox with lost-grid to accomplish what you are trying to accomplish.
